sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ninja-build

language: python
python:
  - "2.7"
install:
  - "pip install -r parsers/requirements.txt"
script: ninja -C parsers/ test
