dist: xenial
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ninja-build

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - "pip3 install -r parsers/requirements.txt"
script: ninja -C parsers/ test
